name: Auto Push Automation

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:


permissions:
  contents: write


jobs:

  automation:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Check for changes
      run: |
        git status


    - name: Auto Commit and Push
      run: |
        git config --global user.name "Likethan K J"
        git config --global user.email "likethankj751@gmail.com"

        git add .

        git diff --cached --quiet || git commit -m "Automated update"

        git push